### ISSUE TITLE
Two-Factor Authentication doesn't have a button

### ISSUE THREAD

**Issue by zenspider** [bellebethcooper/cashew#64]
![screen shot 2019-02-06 at 16 50 50](https://user-images.githubusercontent.com/9832/52383733-6e11ca80-2a2f-11e9-88c4-33615b7894db.png)

**Comment by zenspider** [comment]
Ugh. twice as large because retina and stupid screen grab... sorry.

**Comment by bellebethcooper** [comment]
Sorry for the radio silence! I wasn't getting any GitHub notifications for this repo. This issue will probably be redundant when #5 is done, but this one could be fixed in the meantime.

**Comment by bellebethcooper** [comment]
This was due to removing the `CloudKit` syncing stuff, sorry. I've fixed it for an upcoming version.
